### ISSUE TITLE
It's possible to get through walls

### ISSUE THREAD

**Issue by soverthe** [carykh/SpiderEvoSim#1]
I don't know what caused this but I got through this small wall in-between the two rooms and I couldn't manage to get back, the playback speed was really high so that might've affected this

![image](https://github.com/user-attachments/assets/72799f08-662b-4ce5-8fad-ed0696b8ad70)

**Comment by kosmaaa** [comment]
use shift to noclip through walls

**Comment by soverthe** [comment]
Oh I see, I must've just pressed shift then

**Comment by juanchoco176** [comment]
t
