### ISSUE TITLE
Unrecoverable error occurs whenever i try to open the game

### ISSUE THREAD

**Issue by juanchoco176** [carykh/SpiderEvoSim#10]
I am new to this, i might be doing something wrong but everytime i try to open the game, it shows "unrecoverable error" and proccessing closes, Can someone help me?
![Captura de pantalla 2024-11-01 225955](https://github.com/user-attachments/assets/5fb76f3d-919d-4ad6-a641-da1d6e7a3170)

**Comment by AlkalineSphere** [comment]
This is a Processing 4.3 game

**Comment by hefnar** [comment]
* download and install processing 4.x  https://processing.org/
* download the repository, unzip it
* open spiderevosim.pde using processing 4.x
* sketch -> import library -> manage libraries -> download "sound"
* start the program by clicking on the play button

**Comment by juanchoco176** [comment]
Yes i've found that out now, i have the sound library but when i try to run it, it returns a lot of errors which i don't know how to fix.

**Comment by juanchoco176** [comment]
I've managed to run the game now, Thanks for your help!

**Comment by juanchoco176** [comment]
To open it by the way, make sure to REMOVE the sketch properties, open spiderevosim.pde, and then make sure spiderevosim.pde is MAIN, You may open it by doing this

> Open The spiderevosim zipped file

> Delete the sketch.properties file

> sketch -> import library -> manage libraries -> download the "sound" library and import it into the sketch

> Make sure to run the spiderevosim.pde file after deleting sketch.properties, or this may set another pde like button as main, making it useless.

> After you do that, open processing 4, if you dont have processing 4, Download it here. https://processing.org/

> After installing processing 4, run spiderevosim.pde, and then run the game, if you forgot in the last 3 times i mentioned, delete sketch.properties before running spiderevosim.pde, because if you dont "Button" will be the preset main.

**Comment by jeffrey2763** [comment]
i cant find the sketch.properties file

**Comment by DefinetlyMartyYT** [comment]
the sketch.properties file is not there, you cant see it. click view then show and then unseen files or soth
