### ISSUE TITLE
camera keeps tilting to the left

### ISSUE THREAD

**Issue by SvenWhy** [carykh/SpiderEvoSim#2]
https://github.com/user-attachments/assets/f7c2d4bc-97d4-4c46-a15b-49070e8ffae9

**Comment by kosmaaa** [comment]
change the center_x variable to 960 at line 4 in spiderevosim.pde, cary must've left it at 961 before uploading the files lol

**Comment by hefnar** [comment]
fourth line in main:

int CENTER_X = 960; // try setting this to 960 or 961 if there is horizontal camera-pan-drifting

**Comment by carykh** [comment]
Oh yeah, on some machines, when CENTER_X is set to 960, the camera drifts, and on other machines, if it's set to 961, it drifts. So I made it a variable you can fix yourself!

But I think "960" makes a lot more sense logically, so I just edited the code to say "960" now

**Comment by AlkalineSphere** [comment]
this issue should be closed since it's fixed

**Comment by juanchoco176** [comment]
close the issue
