### ISSUE TITLE
I am terrible at downloading

### ISSUE THREAD

**Issue by Bransonskull** [carykh/SpiderEvoSim#6]
It's not about the game but I cant Download it Make sure to respond as quick as you can

**Comment by SillyZAK-0** [comment]
click the code button and then download as a .zip

**Comment by Nacroni** [comment]
you can either clone the repository or download it as a ZIP file as @SillyZAK-0 mentioned above.

**Comment by Bransonskull** [comment]
Thanks also you could tell your problems down here now I won't close it Until thE owner tells me to
