### ISSUE TITLE
Button issue

### ISSUE THREAD

**Issue by SillyZAK-0** [carykh/SpiderEvoSim#7]
when running, it gives an error that states that the button class cannot be within a PDE file with the same name. upon changing this it gives more errors this spawning code

**Comment by Bransonskull** [comment]
i cant download

**Comment by hefnar** [comment]
you have to open spiderevosim.pde first, which makes it the main file.

you tried to make button main which generated this error

**Comment by SillyZAK-0** [comment]
yeah, i now realize that

**Comment by hefnar** [comment]
did your mother never teach you to say "please" and "thank you"?
